fix silly target file extension error causing error -32
With a source with with mpeg2 video and mp2 audio ...

[mpeg @ 000001baf5ed5b00] Unsupported audio codec. Must be one of mp1, mp2, mp3, 16-bit pcm_dvd, pcm_s16be, ac3 or dts.
[out#0/mpeg @ 000001baf5ecb7c0] Could not write header (incorrect codec parameters ?): Invalid argument
[vf#0:0 @ 000001baf5f1db40] Error sending frames to consumers: Invalid argument
[vf#0:0 @ 000001baf5f1db40] Task finished with error code: -22 (Invalid argument)
[vf#0:0 @ 000001baf5f1db40] Terminating thread with return code -22 (Invalid argument)
...
Error: fwrite() call failed when writing frame: 19, plane: 0, errno: 32

An output file with extension .mpg cannot contain aac audio so it aborts with that error.
Simply changing the output file extension to .mp4 fixed it (since a .mp4 file can contain aac)